print('Введите 6 этапов развития человека:')
print()
a = input('1 этап: ')
b = input('2 этап: ')
c = input('3 этап: ')
d = input('4 этап: ')
e = input('5 этап: ')
f = input('6 этап: ')
print()
print('Эволюция человека:')
print(a, b, c, d, e, f, sep='=>')